create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  bio text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role = 'admin')
);

create table if not exists public.genres (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  description text,
  cover_url text,
  genre_id bigint references public.genres (id) on delete set null,
  published_year integer check (published_year between 0 and 9999)
);

create table if not exists public.user_books (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  book_id bigint not null references public.books (id) on delete cascade,
  status text not null check (status in ('want_to_read', 'reading', 'finished', 'abandoned')),
  started_at date,
  finished_at date,
  progress_pages integer not null default 0 check (progress_pages >= 0),
  unique (user_id, book_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  book_id bigint not null references public.books (id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  review_text text,
  is_spoiler boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, book_id)
);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  book_id bigint not null references public.books (id) on delete cascade,
  quote_text text not null,
  page_number integer
);

create table if not exists public.reading_goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  year integer not null check (year between 1900 and 9999),
  target_books integer not null check (target_books > 0),
  unique (user_id, year)
);

create index if not exists user_roles_user_id_idx on public.user_roles (user_id);
create index if not exists genres_slug_idx on public.genres (slug);
create index if not exists books_genre_id_idx on public.books (genre_id);
create index if not exists user_books_user_id_idx on public.user_books (user_id);
create index if not exists user_books_book_id_idx on public.user_books (book_id);
create index if not exists user_books_status_idx on public.user_books (status);
create index if not exists reviews_user_id_idx on public.reviews (user_id);
create index if not exists reviews_book_id_idx on public.reviews (book_id);
create index if not exists quotes_user_id_idx on public.quotes (user_id);
create index if not exists quotes_book_id_idx on public.quotes (book_id);
create index if not exists reading_goals_user_id_idx on public.reading_goals (user_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      nullif(split_part(new.email, '@', 1), ''),
      'Reader'
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.genres enable row level security;
alter table public.books enable row level security;
alter table public.user_books enable row level security;
alter table public.reviews enable row level security;
alter table public.quotes enable row level security;
alter table public.reading_goals enable row level security;

create policy "profiles are publicly readable"
on public.profiles
for select
using (true);

create policy "profiles are editable by owner"
on public.profiles
for insert
with check (auth.uid() = id);

create policy "profiles are updatable by owner"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "profiles are deletable by owner"
on public.profiles
for delete
using (auth.uid() = id);

create policy "roles are readable by owner or admin"
on public.user_roles
for select
using (auth.uid() = user_id or public.is_admin());

create policy "roles are manageable by admin"
on public.user_roles
for insert
with check (public.is_admin());

create policy "roles are updatable by admin"
on public.user_roles
for update
using (public.is_admin())
with check (public.is_admin());

create policy "roles are deletable by admin"
on public.user_roles
for delete
using (public.is_admin());

create policy "genres are publicly readable"
on public.genres
for select
using (true);

create policy "genres are manageable by admin"
on public.genres
for insert
with check (public.is_admin());

create policy "genres are updatable by admin"
on public.genres
for update
using (public.is_admin())
with check (public.is_admin());

create policy "genres are deletable by admin"
on public.genres
for delete
using (public.is_admin());

create policy "books are publicly readable"
on public.books
for select
using (true);

create policy "books are manageable by admin"
on public.books
for insert
with check (public.is_admin());

create policy "books are updatable by admin"
on public.books
for update
using (public.is_admin())
with check (public.is_admin());

create policy "books are deletable by admin"
on public.books
for delete
using (public.is_admin());

create policy "library items are readable by owner"
on public.user_books
for select
using (auth.uid() = user_id);

create policy "library items are insertable by owner"
on public.user_books
for insert
with check (auth.uid() = user_id);

create policy "library items are updatable by owner"
on public.user_books
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "library items are deletable by owner"
on public.user_books
for delete
using (auth.uid() = user_id);

create policy "reviews are readable by owner"
on public.reviews
for select
using (auth.uid() = user_id);

create policy "reviews are insertable by owner"
on public.reviews
for insert
with check (auth.uid() = user_id);

create policy "reviews are updatable by owner"
on public.reviews
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "reviews are deletable by owner"
on public.reviews
for delete
using (auth.uid() = user_id);

create policy "quotes are readable by owner"
on public.quotes
for select
using (auth.uid() = user_id);

create policy "quotes are insertable by owner"
on public.quotes
for insert
with check (auth.uid() = user_id);

create policy "quotes are updatable by owner"
on public.quotes
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "quotes are deletable by owner"
on public.quotes
for delete
using (auth.uid() = user_id);

create policy "reading goals are readable by owner"
on public.reading_goals
for select
using (auth.uid() = user_id);

create policy "reading goals are insertable by owner"
on public.reading_goals
for insert
with check (auth.uid() = user_id);

create policy "reading goals are updatable by owner"
on public.reading_goals
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "reading goals are deletable by owner"
on public.reading_goals
for delete
using (auth.uid() = user_id);